os:
  - osx
language: node_js

node_js:
  - "stable"

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token:  ${process.env.REACT_APP_GITHUB_API}
  keep-history: true
  local_dir: build
  on:
    branch: attempt-2