export default {
	GET_PROVINCES_REQUEST: 'GET_PROVINCES_REQUEST',
	GET_PROVINCES_SUCCESS: 'GET_PROVINCES_SUCCESS',
	GET_PROVINCES_FAIL: 'GET_PROVINCES_FAIL',

	GET_CITIES_REQUEST: 'GET_CITIES_REQUEST',
	GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',
	GET_CITIES_FAIL: 'GET_CITIES_FAIL',

	GET_DISTRICTS_REQUEST: 'GET_DISTRICTS_REQUEST',
	GET_DISTRICTS_SUCCESS: 'GET_DISTRICTS_SUCCESS',
	GET_DISTRICTS_FAIL: 'GET_DISTRICTS_FAIL',

	GET_SUB_DISTRICTS_REQUEST: 'GET_SUB_DISTRICTS_REQUEST',
	GET_SUB_DISTRICTS_SUCCESS: 'GET_SUB_DISTRICTS_SUCCESS',
	GET_SUB_DISTRICTS_FAIL: 'GET_SUB_DISTRICTS_FAIL'
}